import { QuestionDef } from "../engine/bundle-types";
import { RELATIONSHIP_STATUS, RESOLUTION_STATUS, SELECT_ALL, YES_PROBABLY_NO_NOT_SURE, opts, q, when } from "./helpers";

// Operation (Master Build Guide v2 §7.4–§7.5; Functional Specification v1 §2.1 relationship,
// banking/insurance and already-operating additions; Rules Matrix v1 §15 growth intents).
// Follow-ups render only when their component is selected; volumetrics prefer ranges and always
// allow "Not sure".

const has = (component: string) => when.includes("fa.operation.components", component);

export const OPERATION_COMPONENT_QUESTIONS: QuestionDef[] = [
  q({
    id: "O1",
    field_key: "fa.operation.components",
    type: "multi_select",
    title: [
      "Which parts of your operation are important to delivering what you sell today?",
      "¿Qué partes de tu operación son importantes para entregar lo que vendes hoy?",
    ],
    helper: SELECT_ALL,
    options: opts(
      ["manufacturing", "Manufacturing", "Manufactura"],
      ["sourcing_suppliers", "Sourcing / suppliers", "Abastecimiento / proveedores"],
      ["import_export", "Import / export", "Importación / exportación"],
      ["warehousing_inventory", "Warehousing / inventory", "Almacenamiento / inventario"],
      ["freight_transportation", "Freight / transportation", "Transporte de carga"],
      ["last_mile_delivery", "Last-mile delivery", "Entrega de última milla"],
      ["physical_facilities", "Physical facilities", "Instalaciones físicas"],
      ["technology_systems", "Technology / business systems", "Tecnología / sistemas de negocio"],
      ["local_workforce", "Local workforce", "Personal local"],
      ["external_partners", "External partners / distributors", "Socios externos / distribuidores"],
      ["regulated_activities", "Regulated activities", "Actividades reguladas"],
      ["other", "Other", "Otro"],
    ),
  }),
];

export const OPERATION_DETAIL_QUESTIONS: QuestionDef[] = [
  // Manufacturing
  q({
    id: "O_MFG_VOLUME",
    field_key: "fa.operation.manufacturing.monthly_volume",
    type: "quantity",
    applies_when: has("manufacturing"),
    title: ["Roughly how much do you produce per month?", "¿Aproximadamente cuánto producen al mes?"],
    helper: ["An approximate figure is enough — for example, 20,000 units.", "Una cifra aproximada es suficiente; por ejemplo, 20,000 unidades."],
    placeholder: ["Unit (e.g. units, tons, liters)", "Unidad (p. ej. unidades, toneladas, litros)"],
  }),
  q({
    id: "O_MFG_SKU",
    field_key: "fa.operation.manufacturing.sku_range",
    type: "single_select",
    applies_when: has("manufacturing"),
    title: ["How many products or SKUs do you manage?", "¿Cuántos productos o SKU manejan?"],
    options: opts(
      ["lt_10", "Fewer than 10", "Menos de 10"],
      ["10_50", "10–50", "10–50"],
      ["51_250", "51–250", "51–250"],
      ["251_1000", "251–1,000", "251–1,000"],
      ["1000_plus", "More than 1,000", "Más de 1,000"],
    ),
  }),
  // Sourcing
  q({
    id: "O_SRC_SUPPLIERS",
    field_key: "fa.operation.sourcing.critical_supplier_count",
    type: "single_select",
    applies_when: has("sourcing_suppliers"),
    title: ["How many suppliers are critical to your operation?", "¿Cuántos proveedores son críticos para tu operación?"],
    options: opts(
      ["1_5", "1–5", "1–5"],
      ["6_20", "6–20", "6–20"],
      ["21_50", "21–50", "21–50"],
      ["51_plus", "More than 50", "Más de 50"],
      ["not_sure", "Not sure", "No estoy seguro"],
    ),
  }),
  q({
    id: "O_SRC_LOCAL",
    field_key: "fa.operation.sourcing.local_expected",
    type: "single_select",
    applies_when: has("sourcing_suppliers"),
    title: ["Do you expect to source locally in the new market?", "¿Esperas abastecerte localmente en el nuevo mercado?"],
    options: YES_PROBABLY_NO_NOT_SURE,
  }),
  q({
    id: "O_SRC_ITEMS",
    field_key: "fa.operation.sourcing.local_items",
    type: "text",
    applies_when: when.all(has("sourcing_suppliers"), when.in("fa.operation.sourcing.local_expected", "yes", "probably")),
    title: ["What would need to be sourced locally?", "¿Qué necesitarías abastecer localmente?"],
  }),
  q({
    id: "O_SRC_STATUS",
    field_key: "fa.operation.sourcing.relationship_status",
    type: "single_select",
    applies_when: when.all(has("sourcing_suppliers"), when.in("fa.operation.sourcing.local_expected", "yes", "probably", "not_sure")),
    title: ["Where are you with those local suppliers?", "¿Cómo vas con esos proveedores locales?"],
    options: RELATIONSHIP_STATUS,
  }),
  q({
    id: "O_SRC_CONTEXT",
    field_key: "fa.operation.sourcing.relationship_context",
    type: "text",
    required: false,
    applies_when: when.all(has("sourcing_suppliers"), when.in("fa.operation.sourcing.local_expected", "yes", "probably", "not_sure")),
    title: ["Anything useful to know about those supplier relationships?", "¿Algo útil que debamos saber sobre esas relaciones con proveedores?"],
  }),
  // Import / export
  q({
    id: "O_IMP_SHIPMENTS",
    field_key: "fa.operation.import_export.monthly_shipments",
    type: "single_select",
    applies_when: has("import_export"),
    title: ["How many cross-border shipments do you typically handle per month?", "¿Cuántos envíos internacionales manejan normalmente al mes?"],
    options: opts(
      ["lt_5", "Fewer than 5", "Menos de 5"],
      ["5_20", "5–20", "5–20"],
      ["21_100", "21–100", "21–100"],
      ["101_plus", "More than 100", "Más de 100"],
      ["not_sure", "Not sure", "No estoy seguro"],
    ),
  }),
  q({
    id: "O_IMP_CROSS_BORDER",
    field_key: "fa.operation.import_export.cross_border_expected",
    type: "single_select",
    applies_when: has("import_export"),
    title: ["Will goods cross borders in the new operation?", "¿Habrá mercancía cruzando fronteras en la nueva operación?"],
    options: YES_PROBABLY_NO_NOT_SURE,
  }),
  // Warehousing
  q({
    id: "O_WH_MODEL",
    field_key: "fa.operation.warehousing.current_model",
    type: "single_select",
    applies_when: has("warehousing_inventory"),
    title: ["How do you manage inventory today?", "¿Cómo manejan su inventario hoy?"],
    options: opts(
      ["own", "Our own warehouse", "Almacén propio"],
      ["leased", "A leased warehouse", "Almacén rentado"],
      ["third_party_logistics", "A 3PL provider", "Un proveedor 3PL"],
      ["multiple", "Multiple models", "Varios modelos"],
      ["no_inventory", "We don’t hold inventory", "No manejamos inventario"],
    ),
  }),
  q({
    id: "O_WH_LOCAL",
    field_key: "fa.operation.warehousing.local_expected",
    type: "single_select",
    applies_when: has("warehousing_inventory"),
    title: ["Do you expect to hold inventory or warehouse locally?", "¿Esperas tener inventario o almacén local?"],
    options: YES_PROBABLY_NO_NOT_SURE,
  }),
  q({
    id: "O_WH_SCALE",
    field_key: "fa.operation.warehousing.scale",
    type: "quantity",
    required: false,
    applies_when: when.all(has("warehousing_inventory"), when.in("fa.operation.warehousing.local_expected", "yes", "probably")),
    title: ["If you have a rough idea, what scale do you expect?", "Si ya tienes una idea aproximada, ¿qué escala esperas?"],
    units: opts(
      ["pallet_positions", "Pallet positions", "Posiciones de tarima"],
      ["square_meters", "Square meters", "Metros cuadrados"],
      ["orders_per_month", "Orders per month", "Pedidos al mes"],
    ),
  }),
  // Freight
  q({
    id: "O_FRT_FREQUENCY",
    field_key: "fa.operation.freight.frequency",
    type: "single_select",
    applies_when: has("freight_transportation"),
    title: ["How often do you move freight?", "¿Con qué frecuencia mueven carga?"],
    options: opts(
      ["daily", "Daily", "Diario"],
      ["several_weekly", "Several times a week", "Varias veces por semana"],
      ["weekly", "Weekly", "Semanal"],
      ["several_monthly", "Several times a month", "Varias veces al mes"],
      ["occasionally", "Occasionally", "Ocasionalmente"],
    ),
  }),
  q({
    id: "O_FRT_TYPE",
    field_key: "fa.operation.freight.type",
    type: "single_select",
    applies_when: has("freight_transportation"),
    title: ["What type of freight is it?", "¿Qué tipo de carga es?"],
    options: opts(
      ["dry", "Dry", "Seca"],
      ["refrigerated", "Refrigerated", "Refrigerada"],
      ["intermodal", "Intermodal", "Intermodal"],
      ["specialized", "Specialized", "Especializada"],
      ["other", "Other", "Otra"],
      ["not_sure", "Not sure", "No estoy seguro"],
    ),
  }),
  // Last mile
  q({
    id: "O_LM_DELIVERIES",
    field_key: "fa.operation.last_mile.monthly_deliveries",
    type: "single_select",
    applies_when: has("last_mile_delivery"),
    title: ["Roughly how many last-mile deliveries do you make per month?", "¿Aproximadamente cuántas entregas de última milla hacen al mes?"],
    options: opts(
      ["lt_500", "Fewer than 500", "Menos de 500"],
      ["500_5000", "500–5,000", "500–5,000"],
      ["5001_50000", "5,001–50,000", "5,001–50,000"],
      ["50001_plus", "More than 50,000", "Más de 50,000"],
      ["not_sure", "Not sure", "No estoy seguro"],
    ),
  }),
  q({
    id: "O_LM_LOCAL",
    field_key: "fa.operation.last_mile.local_expected",
    type: "single_select",
    applies_when: has("last_mile_delivery"),
    title: ["Do you expect to deliver last-mile locally in the new market?", "¿Esperas hacer entregas de última milla en el nuevo mercado?"],
    options: YES_PROBABLY_NO_NOT_SURE,
  }),
  // Facilities
  q({
    id: "O_FAC_REQUIRED",
    field_key: "fa.operation.facilities.facility_required",
    type: "single_select",
    applies_when: has("physical_facilities"),
    title: ["Will the new operation require a facility?", "¿La nueva operación requerirá instalaciones?"],
    options: opts(
      ["office", "Office", "Oficina"],
      ["warehouse", "Warehouse", "Almacén"],
      ["manufacturing", "Manufacturing", "Planta de manufactura"],
      ["retail", "Retail", "Punto de venta"],
      ["multiple", "Multiple", "Varias"],
      ["no", "No", "No"],
      ["not_sure", "Not sure", "No estoy seguro"],
    ),
  }),
  q({
    id: "O_FAC_LOCATION",
    field_key: "fa.operation.facilities.location_selected",
    type: "single_select",
    applies_when: when.all(
      has("physical_facilities"),
      when.in("fa.operation.facilities.facility_required", "office", "warehouse", "manufacturing", "retail", "multiple"),
    ),
    title: ["Has the location been selected or committed?", "¿Ya se seleccionó o comprometió la ubicación?"],
    options: opts(["yes", "Yes", "Sí"], ["evaluating", "We’re evaluating options", "Estamos evaluando opciones"], ["no", "Not yet", "Todavía no"]),
  }),
  // Technology
  q({
    id: "O_TECH_SYSTEMS",
    field_key: "fa.operation.technology.critical_systems",
    type: "multi_select",
    applies_when: has("technology_systems"),
    title: ["Which business systems are critical today?", "¿Qué sistemas de negocio son críticos hoy?"],
    helper: SELECT_ALL,
    options: opts(
      ["erp", "ERP", "ERP"],
      ["wms", "WMS", "WMS"],
      ["tms", "TMS", "TMS"],
      ["crm", "CRM", "CRM"],
      ["ecommerce", "E-commerce platform", "Plataforma de comercio electrónico"],
      ["proprietary", "Proprietary systems", "Sistemas propios"],
      ["other", "Other", "Otro"],
    ),
  }),
  q({
    id: "O_TECH_INTEGRATION",
    field_key: "fa.operation.technology.integration_expected",
    type: "single_select",
    applies_when: has("technology_systems"),
    title: [
      "Do you expect implementation, integration or adaptation work in the new market?",
      "¿Esperas trabajo de implementación, integración o adaptación en el nuevo mercado?",
    ],
    options: YES_PROBABLY_NO_NOT_SURE,
  }),
  // Workforce
  q({
    id: "O_WF_HIRING",
    field_key: "fa.operation.workforce.local_hiring_expected",
    type: "single_select",
    applies_when: has("local_workforce"),
    title: ["Do you expect to hire locally?", "¿Esperas contratar personal local?"],
    options: YES_PROBABLY_NO_NOT_SURE,
  }),
  q({
    id: "O_WF_HEADCOUNT",
    field_key: "fa.operation.workforce.first_year_headcount",
    type: "single_select",
    applies_when: when.all(has("local_workforce"), when.in("fa.operation.workforce.local_hiring_expected", "yes", "probably")),
    title: ["About how many people during the first year?", "¿Aproximadamente cuántas personas durante el primer año?"],
    options: opts(
      ["1_10", "1–10", "1–10"],
      ["11_50", "11–50", "11–50"],
      ["51_200", "51–200", "51–200"],
      ["201_plus", "More than 200", "Más de 200"],
      ["not_sure", "Not sure", "No estoy seguro"],
    ),
  }),
  // Partners
  q({
    id: "O_PRT_DEPENDENCY",
    field_key: "fa.operation.partners.dependency",
    type: "single_select",
    applies_when: has("external_partners"),
    title: [
      "Will the operation depend on a local partner, distributor, representative or other third party?",
      "¿La operación dependerá de un socio, distribuidor, representante u otro tercero local?",
    ],
    options: YES_PROBABLY_NO_NOT_SURE,
  }),
  q({
    id: "O_PRT_STATUS",
    field_key: "fa.operation.partners.relationship_status",
    type: "single_select",
    applies_when: when.all(has("external_partners"), when.in("fa.operation.partners.dependency", "yes", "probably", "not_sure")),
    title: ["Where are you with that partner?", "¿Cómo vas con ese socio?"],
    options: RELATIONSHIP_STATUS,
  }),
  q({
    id: "O_PRT_CONTEXT",
    field_key: "fa.operation.partners.relationship_context",
    type: "text",
    required: false,
    applies_when: when.all(has("external_partners"), when.in("fa.operation.partners.dependency", "yes", "probably", "not_sure")),
    title: ["Anything useful to know about that partner relationship?", "¿Algo útil que debamos saber sobre esa relación con el socio?"],
  }),
  // Regulated activities
  q({
    id: "O_REG_PERMITS",
    field_key: "fa.operation.regulated.permits_status",
    type: "single_select",
    applies_when: has("regulated_activities"),
    title: [
      "Do you hold permits, certifications or regulatory approvals today?",
      "¿Hoy cuentan con permisos, certificaciones o aprobaciones regulatorias?",
    ],
    options: opts(["yes", "Yes", "Sí"], ["no", "No", "No"], ["not_sure", "Not sure", "No estoy seguro"]),
  }),
  q({
    id: "O_REG_WHICH",
    field_key: "fa.operation.regulated.permits_which",
    type: "text",
    applies_when: when.all(has("regulated_activities"), when.eq("fa.operation.regulated.permits_status", "yes")),
    title: ["Which ones?", "¿Cuáles?"],
  }),
];

export const CAPABILITY_QUESTIONS: QuestionDef[] = [
  q({
    id: "CAP1",
    field_key: "fa.operation.expected_capabilities",
    type: "multi_select",
    title: [
      "Thinking about the new market, which areas do you expect will need to be built, adapted or validated?",
      "Pensando en el nuevo mercado, ¿qué áreas crees que habrá que construir, adaptar o validar?",
    ],
    helper: SELECT_ALL,
    exclusive_values: ["not_sure"],
    options: opts(
      ["legal_corporate", "Legal / corporate", "Legal / corporativo"],
      ["tax", "Tax", "Fiscal"],
      ["accounting", "Accounting", "Contabilidad"],
      ["banking", "Banking", "Banca"],
      ["insurance", "Insurance", "Seguros"],
      ["contracts", "Contracts", "Contratos"],
      ["talent_hr", "Talent / HR", "Talento / recursos humanos"],
      ["payroll", "Payroll", "Nómina"],
      ["facilities", "Facilities", "Instalaciones"],
      ["technology", "Technology", "Tecnología"],
      ["cyber_data", "Cyber / data infrastructure", "Ciberseguridad / infraestructura de datos"],
      ["logistics", "Logistics", "Logística"],
      ["warehousing", "Warehousing", "Almacenamiento"],
      ["customs_trade", "Customs / trade", "Aduanas / comercio exterior"],
      ["suppliers", "Suppliers", "Proveedores"],
      ["manufacturing", "Manufacturing", "Manufactura"],
      ["commercial_strategy", "Commercial strategy", "Estrategia comercial"],
      ["sales_channels", "Sales channels", "Canales de venta"],
      ["marketing", "Marketing", "Marketing"],
      ["regulatory_compliance", "Regulatory compliance", "Cumplimiento regulatorio"],
      ["local_partner_distributor", "Local partner / distributor", "Socio / distribuidor local"],
      ["risk_due_diligence", "Risk / due diligence", "Riesgo / due diligence"],
      ["not_sure", "I’m not sure yet", "Todavía no estoy seguro"],
      ["other", "Other", "Otro"],
    ),
  }),
  q({
    id: "CAP_BANKING",
    field_key: "fa.operation.banking_status",
    type: "single_select",
    applies_when: when.includes("fa.operation.expected_capabilities", "banking"),
    title: ["Where are you with local banking?", "¿Cómo vas con la banca local?"],
    options: RESOLUTION_STATUS,
  }),
  q({
    id: "CAP_INSURANCE",
    field_key: "fa.operation.insurance_status",
    type: "single_select",
    applies_when: when.includes("fa.operation.expected_capabilities", "insurance"),
    title: ["Where are you with insurance for the new operation?", "¿Cómo vas con los seguros para la nueva operación?"],
    options: RESOLUTION_STATUS,
  }),
  q({
    id: "GROWTH1",
    field_key: "fa.operation.growth_focus",
    type: "multi_select",
    applies_when: when.eq("fa.project.stage", "already_operating"),
    title: ["What are you looking to strengthen or change in the market?", "¿Qué buscas fortalecer o cambiar en el mercado?"],
    helper: SELECT_ALL,
    exclusive_values: ["not_sure"],
    options: opts(
      ["grow_sales", "Grow sales or reach new customers", "Crecer ventas o llegar a nuevos clientes"],
      ["improve_local_operation", "Improve or expand our local operation", "Mejorar o ampliar nuestra operación local"],
      ["find_replace_suppliers", "Find or replace suppliers", "Encontrar o reemplazar proveedores"],
      ["find_partners_distributors", "Find new partners or distributors", "Encontrar nuevos socios o distribuidores"],
      ["strengthen_compliance", "Strengthen compliance or third-party controls", "Fortalecer el cumplimiento o los controles sobre terceros"],
      ["improve_logistics", "Improve logistics or supply chain", "Mejorar la logística o la cadena de suministro"],
      ["add_capabilities_infrastructure", "Add capabilities, technology or infrastructure", "Sumar capacidades, tecnología o infraestructura"],
      ["reduce_operating_risk", "Reduce operating risk or dependency", "Reducir riesgos o dependencias operativas"],
      ["explore_growth_opportunity", "Explore a new growth opportunity", "Explorar una nueva oportunidad de crecimiento"],
      ["not_sure", "Not sure yet", "Todavía no estoy seguro"],
    ),
  }),
];
