import type { Locale } from "../fa/engine/bundle-types";

/**
 * Copy for the beeside Strategic Report System's report-only chrome (cover page, footer, and the two
 * points sections that are specific to the executive document rather than the interactive Virtual
 * Snapshot). This is deliberately its own small bundle rather than folded into
 * snapshot/template.ts's SnapshotTemplateCopy or the frontend's ui-copy.ts virtual_snapshot block:
 * report content is generated once and stored alongside a report record (the same lifecycle as the
 * immutable Snapshot's own template copy), and a printed document earns its own voice for a cover
 * page and confidentiality footer that the on-screen product never needs.
 *
 * Section titles/intros that already exist elsewhere (What Stands Out, Opening's three labels,
 * Precision Assessment, How beeside Works With You) are reused here as their own fields rather than
 * re-derived from the frontend bundle, since backend report generation has no access to that bundle
 * mechanism and must stay self-contained and pure.
 */
export interface ReportCopy {
  cover_eyebrow: string;
  cover_subtitle: string;
  cover_confidential: string;
  opening_project_label: string;
  opening_objectives_label: string;
  opening_requirements_label: string;
  opening_requirements_empty: string;
  big_picture_title: string;
  big_picture_intro: string;
  radar_accessible_summary: string;
  stand_out_title: string;
  stand_out_intro: string;
  precision_title: string;
  precision_intro: string;
  precision_points: [string, string, string];
  works_title: string;
  works_intro: string;
  works_points: [string, string, string];
  footer_generated_by: string;
  footer_page_label: string;
}

export const REPORT_COPY_VERSION = "report-copy-1.0.0";

export function buildReportCopyBundle(): Record<Locale, ReportCopy> {
  return {
    en: {
      cover_eyebrow: "Prepared by beeside",
      cover_subtitle: "Strategic Expansion Assessment",
      cover_confidential: "Confidential — prepared exclusively for {{company_name}}.",
      opening_project_label: "Your project",
      opening_objectives_label: "Your objectives",
      opening_requirements_label: "Your requirements",
      opening_requirements_empty: "No fixed constraints or commitments were flagged at the time of this report.",
      big_picture_title: "The big picture",
      big_picture_intro: "Six dimensions of your project, and how clearly each one is defined today.",
      radar_accessible_summary: "Definition by dimension",
      stand_out_title: "What stands out",
      stand_out_intro: "From the big picture, here is where you have a solid foundation and where to focus first.",
      precision_title: "What to expect in Precision Assessment",
      precision_intro:
        "Precision goes deeper on what you've already shared — validating, clarifying and completing the picture your First Assessment started.",
      precision_points: [
        "A dedicated specialist reviews your project in detail.",
        "Open questions and “not sure” answers get resolved with real research.",
        "You receive a validated plan you can act on with confidence.",
      ],
      works_title: "How beeside works with you",
      works_intro: "beeside stays close throughout, translating what we learn into next steps you control.",
      works_points: [
        "A single point of contact guides your project end to end.",
        "You approve each step before we move forward.",
        "Every recommendation is grounded in your own declared priorities.",
      ],
      footer_generated_by: "Generated by beeside · {{date}}",
      footer_page_label: "Page {{page}} of {{total}}",
    },
    es: {
      cover_eyebrow: "Preparado por beeside",
      cover_subtitle: "Evaluación Estratégica de Expansión",
      cover_confidential: "Confidencial — preparado exclusivamente para {{company_name}}.",
      opening_project_label: "Tu proyecto",
      opening_objectives_label: "Tus objetivos",
      opening_requirements_label: "Tus requisitos",
      opening_requirements_empty: "No se señalaron restricciones o compromisos fijos al momento de este reporte.",
      big_picture_title: "El panorama general",
      big_picture_intro: "Seis dimensiones de tu proyecto, y qué tan definida está cada una hoy.",
      radar_accessible_summary: "Nivel de definición por dimensión",
      stand_out_title: "Lo que más destaca",
      stand_out_intro: "Del panorama general, aquí tienes una base sólida y aquí conviene enfocarte primero.",
      precision_title: "Qué esperar en la Evaluación de Precisión",
      precision_intro:
        "Precision profundiza en lo que ya compartiste: valida, aclara y completa el panorama que inició tu First Assessment.",
      precision_points: [
        "Un especialista dedicado revisa tu proyecto a detalle.",
        "Las preguntas abiertas y las respuestas “no estoy seguro” se resuelven con investigación real.",
        "Recibes un plan validado que puedes accionar con confianza.",
      ],
      works_title: "Cómo beeside trabaja contigo",
      works_intro: "beeside te acompaña de cerca en todo momento, traduciendo lo que descubrimos en próximos pasos que tú controlas.",
      works_points: [
        "Un único punto de contacto guía tu proyecto de principio a fin.",
        "Tú apruebas cada paso antes de avanzar.",
        "Cada recomendación se basa en tus propias prioridades declaradas.",
      ],
      footer_generated_by: "Generado por beeside · {{date}}",
      footer_page_label: "Página {{page}} de {{total}}",
    },
  };
}
