import { Bundle, SessionView } from "./types";

export const TEST_BUNDLE: Bundle = {
  schema_version: 1,
  locales: ["en", "es"],
  stages: [
    { id: "project", copy: { en: { label: "Project" }, es: { label: "Proyecto" } } },
    { id: "business", copy: { en: { label: "Business" }, es: { label: "Negocio" } } },
    { id: "operation", copy: { en: { label: "Operation" }, es: { label: "Operación" } } },
    { id: "priorities", copy: { en: { label: "Priorities" }, es: { label: "Prioridades" } } },
    { id: "snapshot", copy: { en: { label: "Snapshot" }, es: { label: "Snapshot" } } },
  ],
  steps: [
    { id: "goal", stage: "project", kind: "questions", question_ids: ["G1", "C1"], copy: { en: { title: "Set your goal" }, es: { title: "Define tu objetivo" } } },
    { id: "business_transition", stage: "business", kind: "transition", question_ids: [], copy: { en: { title: "Now your business." }, es: { title: "Ahora tu negocio." } } },
  ],
  questions: [
    {
      id: "G1",
      field_key: "fa.goal.primary_goal",
      type: "single_select",
      required: true,
      options: [
        { value: "enter_market", copy: { en: "Enter a new market", es: "Entrar a un nuevo mercado" } },
        { value: "not_sure", copy: { en: "Not sure yet", es: "Todavía no estoy seguro" } },
      ],
      copy: { en: { title: "What is the main goal?" }, es: { title: "¿Cuál es el objetivo principal?" } },
    },
    {
      id: "C1",
      field_key: "fa.constraints.items",
      type: "multi_select",
      required: false,
      exclusive_values: ["not_sure"],
      options: [
        { value: "banking", copy: { en: "Banking", es: "Banca" } },
        { value: "insurance", copy: { en: "Insurance", es: "Seguros" } },
        { value: "not_sure", copy: { en: "Not sure", es: "No estoy seguro" } },
      ],
      copy: { en: { title: "What could affect your plan?" }, es: { title: "¿Qué podría afectar tu plan?" } },
    },
  ],
  identity: { personal_email_domains: ["gmail.com"] },
  links: { terms_url: "https://www.beeside.you/termsandconditions", privacy_policy_url: null },
  ui: {
    common: { copy: { en: { continue: "Continue", back: "Back", required_error: "Please answer to continue.", optional: "Optional" }, es: { continue: "Continuar" } } },
    welcome: {
      copy: {
        en: {
          eyebrow: "beeside First Assessment",
          headline: "Your expansion starts with a clearer view.",
          body: "Tell us about your project. We’ll help you identify what’s already defined, what needs attention, and what comes next.",
          cta: "Start your assessment",
          support: "Around 10–15 minutes · Save and continue later",
        },
        es: {
          eyebrow: "beeside First Assessment",
          headline: "Tu expansión empieza con una visión más clara.",
          body: "Cuéntanos sobre tu proyecto. Te ayudaremos a identificar qué ya está definido, qué necesita atención y qué sigue.",
          cta: "Inicia tu evaluación",
          support: "Alrededor de 10–15 minutos · Guarda y continúa después",
        },
      },
    },
    assemble: { copy: { en: { headline: "Putting the pieces together.", body: "We’re assembling your Expansion Snapshot from what you shared." }, es: { headline: "Armando las piezas.", body: "Estamos preparando tu Expansion Snapshot con lo que compartiste." } } },
    virtual_snapshot: {
      copy: {
        en: {
          big_picture_title: "The big picture",
          big_picture_intro: "Six dimensions of your project, and how clearly each one is defined today.",
          radar_accessible_summary: "Definition by dimension",
          stand_out_title: "What stands out",
          stand_out_intro: "From the big picture, here is where you have a solid foundation and where to focus first.",
          opening_project_label: "Your project",
          opening_objectives_label: "Your objectives",
          opening_requirements_label: "Your requirements",
          opening_requirements_empty: "You haven’t flagged any fixed constraints or commitments yet.",
          pathway_stage_empty: "Nothing is placed at this stage yet.",
          dual_profile_accessible_summary: "Definition & Evidence and Execution Demand by dimension",
          dual_profile_not_evaluable: "Not yet evaluable",
          dual_profile_scale_less: "Less defined",
          dual_profile_scale_more: "More defined",
          dual_profile_radar_eyebrow: "Radar view — the same six dimensions, plotted as one shape per series",
          key_reading_title: "Key Reading",
          market_evidence_title: "Market Evidence",
          execution_pressure_title: "Execution Pressure",
          precision_next_heading: "What's next",
          precision_next_item_1: "With Precision Assessment, your identified needs become clear, service ready requirements.",
          precision_next_item_2: "You'll also gain access to the Operation Hub, where your project, progress and next actions are coordinated in one place.",
          precision_next_item_3: "Your Sherpa and selected specialists from The Hive will then bring tailored proposals to your table, ready for review and activation.",
          precision_next_cta: "See what Premium unlocks",
          value_case_kicker: "Why continue with beeside",
          value_case_title: "The value of one coordinated expansion.",
          value_case_intro: "As the operating model becomes more fragmented, more time, cost and coordination shift back to your team. beeside Premium brings the capabilities together in one coordinated system.",
          value_case_pillars_kicker: "What beeside gives you",
          value_case_pillar_sherpa_head: "Your Sherpa",
          value_case_pillar_sherpa_body: "One person, working as an extension of your team.",
          value_case_pillar_oh_head: "Operation Hub",
          value_case_pillar_oh_body: "One platform for tasks, schedule, documents, follow-up.",
          value_case_pillar_hive_head: "The Hive",
          value_case_pillar_hive_body: "Trusted local ecosystem — vetted specialists, coordinated for you.",
          value_case_pillar_advisory_head: "Strategic advisory",
          value_case_pillar_advisory_body: "Support for the bigger decisions, not bundled consulting.",
          value_case_gain_1: "One person and one platform looking after your interests",
          value_case_gain_2: "Activate exactly the services you need, when you need them",
          value_case_gain_3: "Specialist access the moment a decision gets unclear",
          value_case_gain_4: "Continuity and visibility from day one through execution",
          value_case_compare_caption: "Comparison of estimated times, cost and effort for managing landing services.",
          value_case_tier_a_name: "beeside Premium",
          value_case_tier_a_sub: "Coordinated system",
          value_case_tier_b_name: "Hire one local person",
          value_case_tier_b_sub: "One skillset, one point of view",
          value_case_tier_c_name: "Office + one person",
          value_case_tier_c_sub: "Fixed overhead added",
          value_case_tier_d_name: "Office + person + travels",
          value_case_tier_d_sub: "Highest cost, still fragmented",
          value_case_chip_multi_service: "Multi-service activation",
          value_case_chip_specialist_access: "Specialist access",
          value_case_chip_project_visibility: "Project visibility",
          value_case_chip_coordination: "Coordination",
          value_case_chip_curated_ecosystem: "Curated ecosystem",
          value_case_chip_continuity: "Continuity",
          value_case_chip_digital_platform: "24/7 digital platform access",
          value_case_chip_centralized_docs: "Centralized documentation",
          value_case_chip_local_presence: "Local presence",
          value_case_chip_direct_oversight: "Direct oversight",
          value_case_banner_title: "Expand your business. Not your workload.",
          value_case_banner_body: "Every option above still runs through you. beeside is the only one that gives you a coordinated system — so the work of expanding doesn't become a second job.",
          value_case_banner_chip_specialist: "Curated specialist access",
          value_case_banner_chip_visibility: "Centralized project visibility",
          value_case_banner_chip_continuity: "Sherpa continuity",
          value_case_pdf_title: "Your Executive PDF",
          value_case_pdf_body: "The same project story — summary, warnings, radar, capabilities, activation waves, and this comparison — as a standalone document for management, partners or board circulation. Not a printout of this page.",
          value_case_pdf_tag: "We'll also send this PDF to your email.",
          value_case_cta_title: "Ready to make it happen?",
          value_case_cta_button: "Continue with Premium",
          value_case_cta_disclosure: "This Snapshot reflects the information you provided and is not a guarantee of outcomes. Comparison above is illustrative and does not represent guaranteed pricing.",
          night_toggle_night: "Night Shift",
          night_toggle_day: "Day mode",
        },
        es: {
          big_picture_title: "El panorama general",
          big_picture_intro: "Seis dimensiones de tu proyecto, y qué tan definida está cada una hoy.",
          radar_accessible_summary: "Nivel de definición por dimensión",
          stand_out_title: "Lo que más destaca",
          stand_out_intro: "Del panorama general, aquí tienes una base sólida y aquí conviene enfocarte primero.",
          opening_project_label: "Tu proyecto",
          opening_objectives_label: "Tus objetivos",
          opening_requirements_label: "Tus requisitos",
          opening_requirements_empty: "Todavía no has señalado restricciones o compromisos fijos.",
          pathway_stage_empty: "Todavía no hay nada ubicado en esta etapa.",
          dual_profile_accessible_summary: "Definición y Evidencia, y Demanda de Ejecución, por dimensión",
          dual_profile_not_evaluable: "Todavía no evaluable",
          dual_profile_scale_less: "Menos definido",
          dual_profile_scale_more: "Más definido",
          dual_profile_radar_eyebrow: "Vista de radar — las mismas seis dimensiones, graficadas como una forma por serie",
          key_reading_title: "Lectura Clave",
          market_evidence_title: "Evidencia de Mercado",
          execution_pressure_title: "Presión de Ejecución",
          precision_next_heading: "Qué sigue",
          precision_next_item_1: "Con Precision Assessment, tus necesidades identificadas se convierten en requisitos claros y listos para el servicio.",
          precision_next_item_2: "También tendrás acceso al Operation Hub, donde tu proyecto, tu avance y tus próximas acciones se coordinan en un solo lugar.",
          precision_next_item_3: "Tu Sherpa y los especialistas seleccionados de The Hive llevarán propuestas a la medida a tu mesa, listas para revisión y activación.",
          precision_next_cta: "Descubre lo que desbloquea Premium",
          value_case_kicker: "Por qué continuar con beeside",
          value_case_title: "El valor de una expansión coordinada.",
          value_case_intro: "A medida que el modelo operativo se fragmenta, más tiempo, costo y coordinación regresan a tu equipo. beeside Premium reúne las capacidades en un solo sistema coordinado.",
          value_case_pillars_kicker: "Lo que beeside te da",
          value_case_pillar_sherpa_head: "Tu Sherpa",
          value_case_pillar_sherpa_body: "Una persona, como extensión de tu equipo.",
          value_case_pillar_oh_head: "Operation Hub",
          value_case_pillar_oh_body: "Una plataforma para tareas, calendario, documentos y seguimiento.",
          value_case_pillar_hive_head: "The Hive",
          value_case_pillar_hive_body: "Ecosistema local de confianza — especialistas validados, coordinados para ti.",
          value_case_pillar_advisory_head: "Asesoría estratégica",
          value_case_pillar_advisory_body: "Apoyo para las decisiones grandes, no consultoría empaquetada.",
          value_case_gain_1: "Una persona y una plataforma cuidando tus intereses",
          value_case_gain_2: "Activa exactamente los servicios que necesitas, cuando los necesitas",
          value_case_gain_3: "Acceso a especialistas en el momento en que una decisión se vuelve incierta",
          value_case_gain_4: "Continuidad y visibilidad desde el día uno hasta la ejecución",
          value_case_compare_caption: "Comparación de tiempos, costo y esfuerzo estimados para gestionar los servicios de aterrizaje.",
          value_case_tier_a_name: "beeside Premium",
          value_case_tier_a_sub: "Sistema coordinado",
          value_case_tier_b_name: "Contratar a una persona local",
          value_case_tier_b_sub: "Un perfil, un punto de vista",
          value_case_tier_c_name: "Oficina + una persona",
          value_case_tier_c_sub: "Gasto fijo adicional",
          value_case_tier_d_name: "Oficina + persona + viajes",
          value_case_tier_d_sub: "El costo más alto, sigue fragmentado",
          value_case_chip_multi_service: "Activación multiservicio",
          value_case_chip_specialist_access: "Acceso a especialistas",
          value_case_chip_project_visibility: "Visibilidad del proyecto",
          value_case_chip_coordination: "Coordinación",
          value_case_chip_curated_ecosystem: "Ecosistema curado",
          value_case_chip_continuity: "Continuidad",
          value_case_chip_digital_platform: "Acceso a la plataforma digital 24/7",
          value_case_chip_centralized_docs: "Documentación centralizada",
          value_case_chip_local_presence: "Presencia local",
          value_case_chip_direct_oversight: "Supervisión directa",
          value_case_banner_title: "Expande tu negocio. No tu carga de trabajo.",
          value_case_banner_body: "Cada opción anterior sigue dependiendo de ti. beeside es la única que te da un sistema coordinado — para que expandirte no se convierta en un segundo trabajo.",
          value_case_banner_chip_specialist: "Acceso curado a especialistas",
          value_case_banner_chip_visibility: "Visibilidad centralizada del proyecto",
          value_case_banner_chip_continuity: "Continuidad de tu Sherpa",
          value_case_pdf_title: "Tu PDF Ejecutivo",
          value_case_pdf_body: "La misma historia del proyecto — resumen, alertas, radar, capacidades, olas de activación y esta comparación — como documento independiente para gerencia, socios o el consejo. No es una impresión de esta página.",
          value_case_pdf_tag: "También enviaremos este PDF a tu correo.",
          value_case_cta_title: "¿Listo para hacerlo realidad?",
          value_case_cta_button: "Continuar con Premium",
          value_case_cta_disclosure: "Este Snapshot refleja la información que proporcionaste y no es garantía de resultados. La comparación anterior es ilustrativa y no representa precios garantizados.",
          night_toggle_night: "Modo Nocturno",
          night_toggle_day: "Modo Día",
        },
      },
    },
  },
};

export function testView(overrides: Partial<SessionView> = {}): SessionView {
  return {
    questionBankVersion: "fa-qb-1.0.0",
    status: "IN_PROGRESS",
    currentStepId: "goal",
    lastCompletedStepId: null,
    steps: [
      { id: "goal", applicable: true, confirmed: false, missingRequired: ["G1"], questionIds: ["G1", "C1"] },
      { id: "business_transition", applicable: true, confirmed: false, missingRequired: [], questionIds: [] },
    ],
    answers: {},
    dynamicOptions: {},
    finishLaterAvailable: true,
    anotherProjectInMind: null,
    accessUntil: null,
    interfaceLanguage: "en",
    ...overrides,
  };
}

export function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });
}
